In [ ]:
### dictionary
### numpy -> play with arrays(numbers)
### pandas-> dataset
### matplotlib-> data visualization
### seaborn-> data visualization
### scipy-> statistical
### sklearn-> algorithm

###

### NUMPY: Package for multidimesional array

In [1]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(5,78)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77])

In [9]:
np.arange(2,88,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(1,7,8)

array([1.        , 1.85714286, 2.71428571, 3.57142857, 4.42857143,
       5.28571429, 6.14285714, 7.        ])

In [20]:
np.eye(22,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,

In [31]:
np.random.rand(3,5)

array([[0.3348097 , 0.59933461, 0.18171304, 0.97140361, 0.87789343],
       [0.61821705, 0.38064173, 0.07736047, 0.00759173, 0.92153147],
       [0.17846867, 0.90080522, 0.15800075, 0.27964929, 0.25940896]])

In [35]:
arr=np.random.randn(2,4)
arr

array([[ 4.11677527e-04,  9.46177715e-01,  9.01560652e-03,
        -2.73757915e-01],
       [-9.85575864e-01, -8.09372744e-01,  4.10973050e-01,
        -9.89074289e-01]])

In [39]:
np.random.randint(2,100)

45

In [40]:
np.random.randint(20,56,100)

array([43, 45, 39, 27, 32, 27, 29, 40, 53, 26, 51, 40, 20, 29, 33, 23, 24,
       22, 52, 44, 35, 27, 22, 31, 43, 42, 31, 29, 21, 38, 36, 41, 30, 26,
       23, 26, 37, 55, 48, 36, 48, 47, 27, 26, 52, 25, 25, 24, 37, 32, 39,
       40, 41, 34, 28, 25, 36, 27, 46, 49, 32, 31, 48, 53, 41, 55, 51, 51,
       35, 30, 54, 46, 34, 22, 52, 50, 32, 28, 55, 50, 50, 25, 55, 42, 26,
       52, 25, 48, 34, 55, 31, 22, 31, 21, 45, 49, 50, 35, 36, 35])

In [42]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 0, 4, 5, 1, 3, 9, 4, 3, 4, 7, 9, 3, 0, 0, 7, 2, 8, 9, 7, 5, 6,
       2, 9, 5, 0, 0, 5, 4, 3, 6, 2, 4, 3, 8, 5, 7, 5, 4, 4, 5, 1, 7, 6,
       1, 4, 4, 1, 1, 8])

In [43]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [48]:
rand_array.max()

9

In [55]:
rand_array.argmax()

6

In [57]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
a=np.random.rand(2,3)
a

array([[0.67362482, 0.25745141, 0.41686906],
       [0.01046378, 0.64132758, 0.1059935 ]])

In [61]:
a.T

array([[0.67362482, 0.01046378],
       [0.25745141, 0.64132758],
       [0.41686906, 0.1059935 ]])

In [63]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
sample_array[0]

10

In [65]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [66]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [69]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [71]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])