### Two dimesional array

In [2]:
import numpy as np

In [9]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [10]:
sample_matrix[1,2]

21

In [11]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [12]:
sample_matrix[2]

array([56, 76, 24,  7])

In [13]:
smaple_matrix[2]

array([56, 76, 24,  7])

In [14]:
smaple_matrix[:,(2,3)]

array([[ 1, 23],
       [21, 33],
       [24,  7]])

In [16]:
sample_matrix[1,(1,2)]

array([23, 21])

### selection techniques

In [17]:
sample_array=np.arange(30,40)

In [18]:
sample_array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [19]:
sample_array+sample_array

array([60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [21]:
np.exp(sample_array) #exponential

array([1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
       5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
       3.18559318e+16, 8.65934004e+16])

In [23]:
np.sqrt(sample_array)

array([5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

In [24]:
np.log(sample_array)

array([3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [25]:
np.max(sample_array)

39

In [26]:
np.min(sample_array)

30

In [27]:
np.square(sample_array)

array([ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521])

In [28]:
np.std(sample_array) #standard deviation

2.8722813232690143

In [30]:
np.var(sample_array) #variance

8.25

In [31]:
np.mean(sample_array)

34.5

In [34]:
array=np.random.randn(3,4)
array

array([[ 0.90212153,  0.45697924, -0.76191461,  0.98419666],
       [-0.37887144,  1.37075278,  0.00823463, -1.18979299],
       [ 0.53395192,  1.10440359,  0.06934241, -1.16651073]])

In [35]:
np.round(array,decimals=2)

array([[ 0.9 ,  0.46, -0.76,  0.98],
       [-0.38,  1.37,  0.01, -1.19],
       [ 0.53,  1.1 ,  0.07, -1.17]])

In [36]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')